# parameters for Gazebo ROS control plugin
gazebo_ros_control/pid_gains:
    joint_1: {p: 100.0, i: 0.01, d: 10.0}
    joint_2: {p: 100.0, i: 0.01, d: 10.0}
    joint_3: {p: 100.0, i: 0.01, d: 10.0}
    joint_4: {p: 100.0, i: 0.01, d: 10.0}
    joint_5: {p: 100.0, i: 0.01, d: 10.0}
    joint_6: {p: 100.0, i: 0.01, d: 10.0}
    gripper_finger1_joint: {p: 100.0, i: 0.01, d: 10.0}
